### ISSUE TITLE
[BUG] Modules fail due to pydantic 'depricated' issues

### ISSUE THREAD

**Issue by dgraeber** [awslabs/seed-farmer#492]
When updating to SeedFarmer~=3.1.0, my modules that were deploying correctly now fail with the following:

`ImportError: cannot import name 'deprecated' from 'typing_extensions' (/root/.venv/lib/python3.10/site-packages/typing_extensions.py)`

the version of typing-extensions is 4.5.0 (sometimes less than that depending on the module)

How can we correct this?

**Comment by dgraeber** [comment]
This is due to a change to seedfarmer when updating to v2 of pydantic.  There is a dependency of pydantic v2 on the typing-extensions library, which has modified it's package structure.  In order to get your module working again, in the module itself, update the requirements.txt file :

`typing-extensions~=4.6.3`

You can also directly install this library in your deployspec.yaml with pip:

`pip install --upgrade typing-extensions==4.6.3`

**Comment by dgraeber** [comment]
We will add to our docs that this is the minimum version going forward
